language: generic 
sudo: required

services:
  - docker
      
before_install:
  - docker build -t rpmoore8/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rpmoore8/docker-react npm run test

deploy:
  provider: elasticbeaanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-784291128778"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_KEY:
    secure: "$AWS_SECRET_KEY"
